---
abstract: 'DBIx::Class schema sanity checking tests'
author:
  - 'Chisel Wright <chisel@chizography.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DBIx-Class-Schema
requires:
  DBIx::Class::Schema: 0
  FindBin: 0
  Test::More: 0.92
resources:
  bugtracker: http://github.com/chiselwright/test-dbix-class-schema/issues
  homepage: http://github.com/chiselwright/test-dbix-class-schema/tree
  repository: git://github.com/chiselwright/test-dbix-class-schema.git
version: 0.01009
