---
abstract: 'DBIx::Class schema sanity checking tests'
author:
  - 'Chisel Wright <chisel@chizography.net>'
build_requires:
  Carp: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  Test::Builder::Tester: 0
  Test::More: 0.92
  base: 0
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DBIx-Class-Schema
requires:
  DBIx::Class: 0.08
  FindBin: 0
  Test::More: 0.92
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/chiselwright/Test-DBIx-Class-Schema/issues
  repository: git://github.com/chiselwright/test-dbix-class-schema.git
version: 1.0.4
